/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as TopicsSlugRouteImport } from './routes/topics/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as CoursesSlugVideosIndexRouteImport } from './routes/courses/$slug/videos/index'
import { Route as CoursesSlugVideosVideoIdRouteImport } from './routes/courses/$slug/videos/$videoId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugVideosIndexRoute = CoursesSlugVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugVideosVideoIdRoute =
  CoursesSlugVideosVideoIdRouteImport.update({
    id: '/videos/$videoId',
    path: '/videos/$videoId',
    getParentRoute: () => CoursesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/topics/$slug': typeof TopicsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/courses/$slug/videos/$videoId': typeof CoursesSlugVideosVideoIdRoute
  '/courses/$slug/videos/': typeof CoursesSlugVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/topics/$slug': typeof TopicsSlugRoute
  '/about': typeof AboutIndexRoute
  '/auth': typeof AuthIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/courses/$slug/videos/$videoId': typeof CoursesSlugVideosVideoIdRoute
  '/courses/$slug/videos': typeof CoursesSlugVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/topics/$slug': typeof TopicsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/courses/$slug/videos/$videoId': typeof CoursesSlugVideosVideoIdRoute
  '/courses/$slug/videos/': typeof CoursesSlugVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/topics/$slug'
    | '/about/'
    | '/auth/'
    | '/courses/'
    | '/dashboard/'
    | '/events/'
    | '/topics/'
    | '/courses/$slug/videos/$videoId'
    | '/courses/$slug/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/topics/$slug'
    | '/about'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/events'
    | '/topics'
    | '/courses/$slug/videos/$videoId'
    | '/courses/$slug/videos'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/courses/$slug'
    | '/topics/$slug'
    | '/about/'
    | '/auth/'
    | '/courses/'
    | '/dashboard/'
    | '/events/'
    | '/topics/'
    | '/courses/$slug/videos/$videoId'
    | '/courses/$slug/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  TopicsSlugRoute: typeof TopicsSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug/videos/': {
      id: '/courses/$slug/videos/'
      path: '/videos'
      fullPath: '/courses/$slug/videos/'
      preLoaderRoute: typeof CoursesSlugVideosIndexRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/videos/$videoId': {
      id: '/courses/$slug/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/courses/$slug/videos/$videoId'
      preLoaderRoute: typeof CoursesSlugVideosVideoIdRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
  }
}

interface CoursesSlugRouteChildren {
  CoursesSlugVideosVideoIdRoute: typeof CoursesSlugVideosVideoIdRoute
  CoursesSlugVideosIndexRoute: typeof CoursesSlugVideosIndexRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugVideosVideoIdRoute: CoursesSlugVideosVideoIdRoute,
  CoursesSlugVideosIndexRoute: CoursesSlugVideosIndexRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  TopicsSlugRoute: TopicsSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
