/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicsIndexRouteImport } from './routes/topics/index'
import { Route as LiveIndexRouteImport } from './routes/live/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as TopicsSlugRouteImport } from './routes/topics/$slug'
import { Route as LiveSlugRouteImport } from './routes/live/$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses/$slug'
import { Route as AdminPeopleRouteImport } from './routes/admin/people'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses/$slug/index'
import { Route as CoursesSlugEnrollRouteImport } from './routes/courses/$slug/enroll'
import { Route as CoursesSlugCompleteRouteImport } from './routes/courses/$slug/complete'
import { Route as CoursesSlugVideosIndexRouteImport } from './routes/courses/$slug/videos/index'
import { Route as CoursesSlugVideosVideoIdRouteImport } from './routes/courses/$slug/videos/$videoId'
import { Route as CoursesSlugTestTestIdRouteImport } from './routes/courses/$slug/test/$testId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsSlugRoute = TopicsSlugRouteImport.update({
  id: '/topics/$slug',
  path: '/topics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSlugRoute = LiveSlugRouteImport.update({
  id: '/live/$slug',
  path: '/live/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPeopleRoute = AdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugEnrollRoute = CoursesSlugEnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugCompleteRoute = CoursesSlugCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugVideosIndexRoute = CoursesSlugVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => CoursesSlugRoute,
} as any)
const CoursesSlugVideosVideoIdRoute =
  CoursesSlugVideosVideoIdRouteImport.update({
    id: '/videos/$videoId',
    path: '/videos/$videoId',
    getParentRoute: () => CoursesSlugRoute,
  } as any)
const CoursesSlugTestTestIdRoute = CoursesSlugTestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => CoursesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/people': typeof AdminPeopleRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/live/$slug': typeof LiveSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/live/': typeof LiveIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/courses/$slug/complete': typeof CoursesSlugCompleteRoute
  '/courses/$slug/enroll': typeof CoursesSlugEnrollRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/courses/$slug/test/$testId': typeof CoursesSlugTestTestIdRoute
  '/courses/$slug/videos/$videoId': typeof CoursesSlugVideosVideoIdRoute
  '/courses/$slug/videos/': typeof CoursesSlugVideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/people': typeof AdminPeopleRoute
  '/live/$slug': typeof LiveSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/live': typeof LiveIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/courses/$slug/complete': typeof CoursesSlugCompleteRoute
  '/courses/$slug/enroll': typeof CoursesSlugEnrollRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
  '/courses/$slug/test/$testId': typeof CoursesSlugTestTestIdRoute
  '/courses/$slug/videos/$videoId': typeof CoursesSlugVideosVideoIdRoute
  '/courses/$slug/videos': typeof CoursesSlugVideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/people': typeof AdminPeopleRoute
  '/courses/$slug': typeof CoursesSlugRouteWithChildren
  '/live/$slug': typeof LiveSlugRoute
  '/topics/$slug': typeof TopicsSlugRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/live/': typeof LiveIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/courses/$slug/complete': typeof CoursesSlugCompleteRoute
  '/courses/$slug/enroll': typeof CoursesSlugEnrollRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/courses/$slug/test/$testId': typeof CoursesSlugTestTestIdRoute
  '/courses/$slug/videos/$videoId': typeof CoursesSlugVideosVideoIdRoute
  '/courses/$slug/videos/': typeof CoursesSlugVideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/admin/content'
    | '/admin/people'
    | '/courses/$slug'
    | '/live/$slug'
    | '/topics/$slug'
    | '/about/'
    | '/admin/'
    | '/auth/'
    | '/courses/'
    | '/dashboard/'
    | '/events/'
    | '/live/'
    | '/topics/'
    | '/courses/$slug/complete'
    | '/courses/$slug/enroll'
    | '/courses/$slug/'
    | '/courses/$slug/test/$testId'
    | '/courses/$slug/videos/$videoId'
    | '/courses/$slug/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/admin/content'
    | '/admin/people'
    | '/live/$slug'
    | '/topics/$slug'
    | '/about'
    | '/admin'
    | '/auth'
    | '/courses'
    | '/dashboard'
    | '/events'
    | '/live'
    | '/topics'
    | '/courses/$slug/complete'
    | '/courses/$slug/enroll'
    | '/courses/$slug'
    | '/courses/$slug/test/$testId'
    | '/courses/$slug/videos/$videoId'
    | '/courses/$slug/videos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/admin/content'
    | '/admin/people'
    | '/courses/$slug'
    | '/live/$slug'
    | '/topics/$slug'
    | '/about/'
    | '/admin/'
    | '/auth/'
    | '/courses/'
    | '/dashboard/'
    | '/events/'
    | '/live/'
    | '/topics/'
    | '/courses/$slug/complete'
    | '/courses/$slug/enroll'
    | '/courses/$slug/'
    | '/courses/$slug/test/$testId'
    | '/courses/$slug/videos/$videoId'
    | '/courses/$slug/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CoursesSlugRoute: typeof CoursesSlugRouteWithChildren
  LiveSlugRoute: typeof LiveSlugRoute
  TopicsSlugRoute: typeof TopicsSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$slug': {
      id: '/topics/$slug'
      path: '/topics/$slug'
      fullPath: '/topics/$slug'
      preLoaderRoute: typeof TopicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$slug': {
      id: '/live/$slug'
      path: '/live/$slug'
      fullPath: '/live/$slug'
      preLoaderRoute: typeof LiveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/people': {
      id: '/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminPeopleRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/enroll': {
      id: '/courses/$slug/enroll'
      path: '/enroll'
      fullPath: '/courses/$slug/enroll'
      preLoaderRoute: typeof CoursesSlugEnrollRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/complete': {
      id: '/courses/$slug/complete'
      path: '/complete'
      fullPath: '/courses/$slug/complete'
      preLoaderRoute: typeof CoursesSlugCompleteRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/videos/': {
      id: '/courses/$slug/videos/'
      path: '/videos'
      fullPath: '/courses/$slug/videos/'
      preLoaderRoute: typeof CoursesSlugVideosIndexRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/videos/$videoId': {
      id: '/courses/$slug/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/courses/$slug/videos/$videoId'
      preLoaderRoute: typeof CoursesSlugVideosVideoIdRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
    '/courses/$slug/test/$testId': {
      id: '/courses/$slug/test/$testId'
      path: '/test/$testId'
      fullPath: '/courses/$slug/test/$testId'
      preLoaderRoute: typeof CoursesSlugTestTestIdRouteImport
      parentRoute: typeof CoursesSlugRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminPeopleRoute: typeof AdminPeopleRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminPeopleRoute: AdminPeopleRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CoursesSlugRouteChildren {
  CoursesSlugCompleteRoute: typeof CoursesSlugCompleteRoute
  CoursesSlugEnrollRoute: typeof CoursesSlugEnrollRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
  CoursesSlugTestTestIdRoute: typeof CoursesSlugTestTestIdRoute
  CoursesSlugVideosVideoIdRoute: typeof CoursesSlugVideosVideoIdRoute
  CoursesSlugVideosIndexRoute: typeof CoursesSlugVideosIndexRoute
}

const CoursesSlugRouteChildren: CoursesSlugRouteChildren = {
  CoursesSlugCompleteRoute: CoursesSlugCompleteRoute,
  CoursesSlugEnrollRoute: CoursesSlugEnrollRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
  CoursesSlugTestTestIdRoute: CoursesSlugTestTestIdRoute,
  CoursesSlugVideosVideoIdRoute: CoursesSlugVideosVideoIdRoute,
  CoursesSlugVideosIndexRoute: CoursesSlugVideosIndexRoute,
}

const CoursesSlugRouteWithChildren = CoursesSlugRoute._addFileChildren(
  CoursesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CoursesSlugRoute: CoursesSlugRouteWithChildren,
  LiveSlugRoute: LiveSlugRoute,
  TopicsSlugRoute: TopicsSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
